namespace: irkhamdivistant
name: Syncthing
version: 1.0.0
readme: README.md
authors: ["Irkham Hidayat"]
description: Syncthing
license: AGPL-3.0-or-later
repository: https://github.com/irkhamdivistant/ansible-syncthing
tags: [Syncthing, service, linux]
dependencies: {}
