all:
  children:
    vms:
      hosts:
        drc:
          ansible_host: 34.31.135.39
          ansible_user: drc_user
          ansible_password: devops123
          ansible_become: true
          ansible_become_method: sudo
          syncthing_enabled: true
          syncthing_folders:
            - id: sample-application/sample-php-service3
              path: /var/www/staging/sample-php-service3
              type: receiveonly
