all:
  children:
    vms:
      hosts:
        dc:
          ansible_host: 34.134.80.85
          ansible_user: dc_user
          ansible_password: devops123
          ansible_become: true
          ansible_become_method: sudo
          syncthing_enabled: true
          syncthing_folders:
            - id: sample-application/sample-java-service3
              path: /opt/apps/staging/sample-java-service3
              type: sendonly
